-- Most organizations highly customize their instance of salesforce to match the specific business
-- process they use.

-- As a result for the salesforce.com adapter it's desireable to define the sales force objects separately
-- from the core code.

local objectDefs = {}

objectDefs.user = {object='User', fields={
                      UserPreferencesApexPagesDeveloperMode="?",
                      FirstName="?",
                      Division="?",
                      FederationIdentifier="?",
                      UserPreferencesLightningExperiencePreferred="?",
                      Alias="?",
                      UserPreferencesHideCSNDesktopTask="?",
                      DelegatedApproverId="?",
                      EmailEncodingKey="?",
                      LastLoginDate="?",
                      UserType="?",
                      OfflineTrialExpirationDate="?",
                      CallCenterId="?",
                      EmployeeNumber="?",
                      City="?",
                      LastModifiedById="?",
                      UserPermissionsInteractionUser="?",
                      CommunityNickname="?",
                      MobilePhone="?",
                      Extension="?",
                      ContactId="?",
                      State="?",
                      UserRoleId="?",
                      SmallPhotoUrl="?",
                      Fax="?",
                      UserPermissionsOfflineUser="?",
                      UserPermissionsMobileUser="?",
                      CreatedById="?",
                      UserPermissionsAvantgoUser="?",
                      ForecastEnabled="?",
                      UserPreferencesHideCSNGetChatterMobileTask="?",
                      LastPasswordChangeDate="?",
                      UserPreferencesDisableAutoSubForFeeds="?",
                      CurrencyIsoCode="?",
                      Country="?",
                      Phone="?",
                      DigestFrequency="?",
                      Email="?",
                      UserPreferencesActivityRemindersPopup="?",
                      ReceivesInfoEmails="?",
                      AboutMe="?",
                      UserPermissionsCallCenterAutoLogin="?",
                      CompanyName="?",
                      LastModifiedDate="?",
                      ReceivesAdminInfoEmails="?",
                      LastName="?",
                      Street="?",
                      Username="?",
                      FullPhotoUrl="?",
                      CurrentStatus="?",
                      AccountId="?",
                      LanguageLocaleKey="?",
                      ProfileId="?",
                      SystemModstamp="?",
                      OfflinePdaTrialExpirationDate="?",
                      Department="?",
                      CreatedDate="?",
                      UserPreferencesOptOutOfTouch="?",
                      PostalCode="?",
                      UserPreferencesReminderSoundOff="?",
                      Name="?",
                      IsActive="?",
                      UserPreferencesEventRemindersCheckboxDefault="?",
                      LocaleSidKey="?",
                      UserPreferencesTaskRemindersCheckboxDefault="?",
                      UserPermissionsSFContentUser="?",
                      UserPermissionsMarketingUser="?",
                      ManagerId="?",
                      TimeZoneSidKey="?",
                      DefaultCurrencyIsoCode="?",
                      Title="?"}}

objectDefs.contact =  {object='Contact', fields={
                      CreatedDate="Date created",
                      FirstName="First name of contact",
                      LastCURequestDate="?",
                      CurrencyIsoCode="?",
                      EmailBouncedDate="?",
                      Email="Email of contact",
                      HasOptedOutOfEmail="?",
                      AccountId="AccountID of the contact",
                      LastModifiedDate="When last modified",
                      LastName="Last name of contact",
                      LastModifiedById="Who modified this",
                      SystemModstamp="?",
                      ReportsToId="?",
                      Department="What department",
                      MobilePhone="Their mobile phone",
                      Title="Title of contact - CEO etc.",
                      MasterRecordId="?",
                      CreatedById="Who created this",
                      LastActivityDate="Last activity date",
                      OwnerId="Owner of this contact",
                      IsDeleted="Has this contact been deleted",
                      Name="?",
                      EmailBouncedReason="?",
                      Salutation="How to greet them",
                      Fax="FAX number",
                      LastCUUpdateDate="?"}}


objectDefs.queueSobject = {object='QueueSobject', fields={
                      SystemModstamp="A field",
                      QueueId="A field",
                      SobjectType="A field",
                      CreatedById="A field"}}



objectDefs.note = {object='Note', fields={
                      IsPrivate="A field",
                      LastModifiedDate="A field",
                      CreatedDate="A field",
                      ParentId="A field",
                      Body="A field",
                      OwnerId="A field",
                      IsDeleted="A field",
                      CreatedById="A field",
                      LastModifiedById="A field",
                      SystemModstamp="A field",
                      Title="A field"}}


objectDefs.product2 = {object='Product2', fields={
                      Description="A field",
                      CreatedDate="A field",
                      ProductCode="A field",
                      IsActive="A field",
                      IsDeleted="A field",
                      Name="A field",
                      LastModifiedById="A field",
                      Family="A field",
                      CreatedById="A field",
                      SystemModstamp="A field",
                      LastModifiedDate="A field"}}

objectDefs.opportunity = {object='Opportunity', fields={
                      CreatedDate="?",
                      CloseDate="?",
                      StageName="?",
                      CreatedById="?",
                      SyncedQuoteId="?",
                      Probability="?",
                      CurrencyIsoCode="?",
                      CampaignId="?",
                      RecordTypeId="?",
                      ForecastCategoryName="?",
                      AccountId="?",
                      ForecastCategory="?",
                      LastModifiedDate="?",
                      HasOpportunityLineItem="?",
                      LastModifiedById="?",
                      SystemModstamp="?",
                      FiscalYear="?",
                      Fiscal="?",
                      IsClosed="?",
                      LeadSource="?",
                      OwnerId="?",
                      IsDeleted="?",
                      Name="?",
                      LastActivityDate="?",
                      Type="?",
                      FiscalQuarter="?",
                      Pricebook2Id="?",
                      IsWon="?"}}

objectDefs.account = {object='Account', fields={
                      CreatedDate="A field",
                      Industry="A field",
                      CurrencyIsoCode="?",
                      IsDeleted="A field",
                      LastModifiedDate="A field",
                      LastModifiedById="A field",
                      SystemModstamp="A field",
                      MasterRecordId="A field",
                      CreatedById="A field",
                      ParentId="A field",
                      LastActivityDate="A field",
                      OwnerId="A field",
                      Name="A field"}}

return objectDefs

